// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpEUvqgM4QcRhFeBRNeC-OTXfUj63qu2U',
    appId: '1:16011954749:web:3c9402552c7c3718af3854',
    messagingSenderId: '16011954749',
    projectId: 'chat-aa4a5',
    authDomain: 'chat-aa4a5.firebaseapp.com',
    storageBucket: 'chat-aa4a5.appspot.com',
    measurementId: 'G-HQQ3SE0YHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRh5GQrRycE7V_k6osQctbUIzFgCIK6I',
    appId: '1:16011954749:android:dcd2cccf83d1eb58af3854',
    messagingSenderId: '16011954749',
    projectId: 'chat-aa4a5',
    storageBucket: 'chat-aa4a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWSx8j8KE2NBaPn6xOFco7s94TOa6LbmM',
    appId: '1:16011954749:ios:769736abe2471681af3854',
    messagingSenderId: '16011954749',
    projectId: 'chat-aa4a5',
    storageBucket: 'chat-aa4a5.appspot.com',
    iosClientId: '16011954749-0eolkdmq163bughg6tfqm7gr7j1f79uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWSx8j8KE2NBaPn6xOFco7s94TOa6LbmM',
    appId: '1:16011954749:ios:769736abe2471681af3854',
    messagingSenderId: '16011954749',
    projectId: 'chat-aa4a5',
    storageBucket: 'chat-aa4a5.appspot.com',
    iosClientId: '16011954749-0eolkdmq163bughg6tfqm7gr7j1f79uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
